/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author ivan
 */
/**
 * INTERFAZ GRAFICA PARA LA GESTION DE ACTIVIDAD
 * PROPORCIONA FUNCIONALIDADES PARA LA GESTION COMPLETA DEL SISTEMA DE GIMNASIO
 * 
 * @author SISTEMA DE GESTION DE GIMNASIO
 * @version 1.0
 */
public class VistaActividad extends javax.swing.JPanel {

    /**
     * Creates new form VistaActividad
     */
    public VistaActividad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableActividades = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButtonEstadisticas = new javax.swing.JButton();
        jButtonFiltrar = new javax.swing.JButton();
        jButtonNuevaActividad = new javax.swing.JButton();
        jButtonBajaActividad = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jTableActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableActividades);

        jScrollPane1.setViewportView(jScrollPane2);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButtonEstadisticas.setText("Estadisticas");
        jPanel1.add(jButtonEstadisticas);

        jButtonFiltrar.setText("Filtrar");
        jPanel1.add(jButtonFiltrar);

        jButtonNuevaActividad.setText("Nueva Actividad");
        jButtonNuevaActividad.setActionCommand("NuevaActividad");
        jPanel1.add(jButtonNuevaActividad);

        jButtonBajaActividad.setText("Baja Actividad");
        jButtonBajaActividad.setActionCommand("BajaActividad");
        jPanel1.add(jButtonBajaActividad);

        jButtonActualizar.setText("Actualizar");
        jPanel1.add(jButtonActualizar);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonActualizar;
    public javax.swing.JButton jButtonBajaActividad;
    public javax.swing.JButton jButtonEstadisticas;
    public javax.swing.JButton jButtonFiltrar;
    public javax.swing.JButton jButtonNuevaActividad;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTableActividades;
    // End of variables declaration//GEN-END:variables
}
