/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author ivan
 */
public class VistaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuInicio = new javax.swing.JMenu();
        menuItemInicio = new javax.swing.JMenuItem();
        MenuMonitores = new javax.swing.JMenu();
        menuItemGestionMonitores = new javax.swing.JMenuItem();
        MenuSocios = new javax.swing.JMenu();
        menuItemGestionSocios = new javax.swing.JMenuItem();
        MenuActividades = new javax.swing.JMenu();
        menuItemGestionActividades = new javax.swing.JMenuItem();
        jMenuInscripciones = new javax.swing.JMenu();
        jMenuItemInscripciones = new javax.swing.JMenuItem();
        MenuSalir = new javax.swing.JMenu();
        menuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        MenuInicio.setText("Inicio");

        menuItemInicio.setText("menuItemInicio");
        MenuInicio.add(menuItemInicio);

        jMenuBar1.add(MenuInicio);

        MenuMonitores.setText("Monitores");

        menuItemGestionMonitores.setText("menuItemGestionMonitores");
        MenuMonitores.add(menuItemGestionMonitores);

        jMenuBar1.add(MenuMonitores);

        MenuSocios.setText("Socios");

        menuItemGestionSocios.setText("menuItemGestionSocios");
        MenuSocios.add(menuItemGestionSocios);

        jMenuBar1.add(MenuSocios);

        MenuActividades.setText("Actividades");

        menuItemGestionActividades.setText("menuItemGestionActividades");
        MenuActividades.add(menuItemGestionActividades);

        jMenuBar1.add(MenuActividades);

        jMenuInscripciones.setText("Inscripciones");

        jMenuItemInscripciones.setText("menuItemInscripciones");
        jMenuItemInscripciones.setActionCommand("menuItemInscripciones");
        jMenuInscripciones.add(jMenuItemInscripciones);

        jMenuBar1.add(jMenuInscripciones);

        MenuSalir.setText("Salir");

        menuItemSalir.setText("menuItemSalir");
        MenuSalir.add(menuItemSalir);

        jMenuBar1.add(MenuSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu MenuActividades;
    public javax.swing.JMenu MenuInicio;
    public javax.swing.JMenu MenuMonitores;
    public javax.swing.JMenu MenuSalir;
    public javax.swing.JMenu MenuSocios;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenu jMenuInscripciones;
    public javax.swing.JMenuItem jMenuItemInscripciones;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JMenuItem menuItemGestionActividades;
    public javax.swing.JMenuItem menuItemGestionMonitores;
    public javax.swing.JMenuItem menuItemGestionSocios;
    public javax.swing.JMenuItem menuItemInicio;
    public javax.swing.JMenuItem menuItemSalir;
    // End of variables declaration//GEN-END:variables
}


